apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_PASSWORD
          value: "abc123"
        - name: DATABASE_USER
          value: "yon"
        - name: DATABASE_NAME
          value: "kube"
        - name: DATABASE_HOST
          value: "db"
        - name: DATABASE_PORT
          value: "3306"